### ISSUE TITLE
add a .clap release

### ISSUE THREAD

**Issue by RustoMCSpit** [stevefolta/sfzq#1]

**Comment by stevefolta** [comment]
If I were to create one, would you willing to test it before I published it?  Which distro are you using?  Which DAW?

**Comment by RustoMCSpit** [comment]
linux mint lts and bitwig

**Comment by stevefolta** [comment]
Okay, I've got a candidate.  Could you give it a try?: <https://f001.backblazeb2.com/file/steve-folta/sfzq/sfzq.2024.9.3.clap.tgz>

**Comment by RustoMCSpit** [comment]
put it in github releases

**Comment by stevefolta** [comment]
Did you try it?  Did it work?

**Comment by RustoMCSpit** [comment]
> Did you try it? Did it work?

browser wont download from website

**Comment by stevefolta** [comment]
That's odd.  Try wget or curl, maybe.

**Comment by RustoMCSpit** [comment]
just put it on the release and i'll download it

**Comment by stevefolta** [comment]
I'll release it after you've tested it.

**Comment by stevefolta** [comment]
I really want to get at least that small bit of testing (outside of what I do myself) before releasing it.

**Comment by RustoMCSpit** [comment]
> I really want to get at least that small bit of testing (outside of what I do myself) before releasing it.

i'll build it then and tell you

**Comment by stevefolta** [comment]
I want to get the release-candidate binary tested.  Please download that.

**Comment by RustoMCSpit** [comment]
is that a specific branch or?  i can just download it and build it myself and tell you if it works

**Comment by stevefolta** [comment]
Its a binary .clap file, but built in a specific way (some of the details are mentioned in issue #2), so it can hopefully work on most people's machines.  If wget or curl don't work for you, please let me know what the error is so I can try to figure out a way around your download problem.  Again, I'm hoping you'll be able and willing to test that pre-built binary release candidate.

**Comment by sorrowl** [comment]
I tested the .clap file linked above, and it worked perfectly on my machine. Both .sf2 and .sfz files loaded and played the expected sounds. Didn't do any extra testing, but hope this helps.
Specs:
Arch Linux, kernel 6.11.9-arch1-1
REAPER v7.27
x86_64 processor

**Comment by stevefolta** [comment]
@sorrowl: Thanks for the report!

After getting that, I was about to cut a release.  But then I thought I ought to at least try Linux Mint in a VM.  It worked fine there in Reaper... but not in Bitwig.  After some confusion, I believe I've fixed that.

So here's a new candidate: <https://f001.backblazeb2.com/file/steve-folta/sfzq/sfzq.2024.12.2.clap.tgz>

I hope someone can give this a quick test.  If I don't hear from anyone in a few days, I might just release it anyway.

**Comment by stevefolta** [comment]
I found and fixed an unrelated crashing bug.  And I also discovered that, for some distros, it _does_ need to be built with "-static-libstdc++".  So there's another candidate already: <https://f001.backblazeb2.com/file/steve-folta/sfzq/sfzq.2024.12.3.clap.tgz>.

**Comment by sorrowl** [comment]
Can confirm that the latest version works in REAPER with Arch.

**Comment by stevefolta** [comment]
Thanks, @sorrowl.  I've made a release (that was easy!).  One can only hope it'll work for @RustoMCSpit.  Closing the issue.
